version: '3.7'
services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env
  web:
    build: .
    container_name: web
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

volumes:
  static_value:
  media_value: