# Generated by Django 4.2.7 on 2023-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
